### ISSUE TITLE
SHOW META via SphinxQL

### ISSUE THREAD

**Issue by NMFES** [yiisoft/yii2-sphinx#10]
Hello. How i can fetch meta data using raw sphinxQL (not QueryBuilder) in one query?

$sql = "SELECT * FROM index; SHOW META"
Yii::$app->sphinx->createCommand($sql)->fetchAll();

This returns data for first part of the query (SELECT * FROM index);

**Comment by klimov-paul** [comment]
@NMFES, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
