### ISSUE TITLE
how to orMatch() many times?

### ISSUE THREAD

**Issue by awebc** [yiisoft/yii2-sphinx#100]
### What's expected?
$words=[words1,words2...];
orMatch : words1,words2...
to make an condition like this : (words1) | (words2) | ....
### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           |
| Yii Sphinx version    |
| Sphinx server version |
| PHP version           |
| Operating system      |

**Comment by skvarovski** [comment]
$text = explode(',', '(world1), (world2), (world3)');
        
->match(new Expression(':match',
                [
                    'match' => implode(' | ', $text)
                ]
            ))


use this trick
