### ISSUE TITLE
Method andFilterWhere() NULL value in array

### ISSUE THREAD

**Issue by iluxaar** [yiisoft/yii2-sphinx#105]
| Yii version           | 2.0.15.1
| Yii Sphinx version    | 2.0.10
| PHP version           | 7.2
| Operating system      | centos7

```
Syntax error or access violation: 1064 sphinxql: syntax error, unexpected NULL, expecting CONST_INT
```
```
SELECT COUNT(*) FROM `lot_index` ((`organization_id` IN (NULL, 1939))
```
```
// $organizations is array IDs
$query = LotIndex::find();
$query->andFilterWhere(['organization_id' => $this->organizations]);
```
SearchModel rules:
```
public function rules()
{
    return [
        [['organizations'], 'safe'],
    ];
}
```

**Comment by bitdevelopment** [comment]
Hi, iluxaar,

`andFilterWhere` is not part of sphinx extension, but part of `yii\db`. 

It seems that you sent `(array)` in `andFilterWhere`. This function doesn't filter `IN` arrays. You can resolve this by write query with something like this:

```php
// $organizations is array IDs
$query = LotIndex::find();
$query->andFilterWhere(['organization_id' => array_filter($this->organizations)]);
```

**Comment by iluxaar** [comment]
Thanks, bitdevelopment, It's works.
