### ISSUE TITLE
Allowed memory size of 8589934592 bytes exhausted

### ISSUE THREAD

**Issue by airgram** [yiisoft/yii2-sphinx#109]
### What steps will reproduce the problem?

```
 $provider = new ActiveDataProvider([
      'query' => Post::find()->facets(['author_id', 'category_id']),
      'pagination' => [
          'pageSize' => 20,
      ],
 ]);
```

### What's expected?
Instance of tha data provider.

### What do you get instead?
Infinity loop and fatal error.

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | 2.1.16
| Yii Sphinx version    | 2.0.11
| Sphinx server version | Sphinx 2.2.11-id64-release (95ae9a6)
| PHP version           | 7.1
| Operating system      | macOs Mojave

Extension has broken due this commit: https://github.com/yiisoft/yii2/commit/e1623868f9e95769074312f8582c1709cfcb52a8#diff-3a9563dfdfd2448d1b7edfad3ec14522

It happens because of if meta does not exist methods `prepareModels` and `getPagination` execute in a cycle ([here](https://github.com/yiisoft/yii2-sphinx/blob/master/src/ActiveDataProvider.php#L110) and [here](https://github.com/yiisoft/yii2-sphinx/blob/master/src/ActiveDataProvider.php#L139)).

**Comment by machour** [comment]
Referencing https://github.com/yiisoft/yii2-elasticsearch/issues/201

**Comment by samdark** [comment]
Should work well with master. I've reverted change causing it.

**Comment by maz0717** [comment]
Master what?  Master yii2 or master yii2-sphinx?  I've just ran composer update on my project, and am using yii2-sphinx dev-master and the problem still exists.

...
   - Updating yiisoft/yii2 (2.0.15.1 => 2.0.16): Loading from cache
...
   - Updating yiisoft/yii2-sphinx dev-master (bc22a13 => a9aebd0):  Checking out a9aebd09cf
...
[Tue Feb 26 09:06:27 2019] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /Users/maz/projects/gsys/vendor/yiisoft/yii2/db/ActiveRelationTrait.php on line 72
[Tue Feb 26 09:06:27 2019] 127.0.0.1:50264 [500]: /gallery/recent - Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in /Users/maz/projects/gsys/vendor/yiisoft/yii2/db/ActiveRelationTrait.php on line 72
[Tue Feb 26 09:06:27 2019] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
[Tue Feb 26 09:06:27 2019] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
[Tue Feb 26 09:06:27 2019] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes)

**Comment by machour** [comment]
Master yii2

**Comment by esindger** [comment]
When are you going to release `2.0.12` with this fix?

**Comment by machour** [comment]
@esindger the fix was made in yii2, not in this extension. Please open a new issue if you're still having problems with last version of yii2
