### ISSUE TITLE
Undefined array key when moving to php8.1 with facets

### ISSUE THREAD

**Issue by kulikov6** [yiisoft/yii2-sphinx#127]
I moved from php7.1 to php8.1 and catched an error:

yii\base\ErrorException: Undefined array key "brand" in
/usr/local/www/vendor/yiisoft/yii2-sphinx/src/Query.php:248

because of absence the same field as facet name in Select expression:

                'brand'  => [
                    'select' => [new Expression(brand as code, brand as name BY brand')],
                    'order'  => ['brand' => SORT_ASC],
                    'limit'  => self::FACETS_LIMIT,
                ],

But in php7.1 it works without error.
The simplest solution is:
$rawFacetResult['value'] = $rawFacetResult[strtolower($facet['value'])] **?? null**;

But I cant change the library.
When i tried this:

                'brand'  => [
                    'select' => [new Expression('brand as code,  brand as brand, brand as name BY brand')],
                    'order'  => ['brand' => SORT_ASC],
                    'limit'  => self::FACETS_LIMIT,
                ],

I have got error from sphinx:
parse error: Sphinx expr: syntax error, unexpected $end, expecting TOK_EQ or TOK_NE near '' in
/usr/local/www/vendor/yiisoft/yii2/db/DataReader.php:154

So, after some attemps, I found a workaround:

                'brand'  => [
                    'select' => [new Expression('brand as name, brand as code, brand as brand BY brand')],
                    'order'  => ['brand' => SORT_ASC],
                    'limit'  => self::FACETS_LIMIT,
                ],

For backward compatibility to reproduce an old behavior I suggest to add a null coalescing operator:

$rawFacetResult['value'] = $rawFacetResult[strtolower($facet['value'])] ?? null;

Many work hours will saved :)

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | 2.0.42
| Yii Sphinx version    | 2.0.14
| Sphinx server version | 3.?
| PHP version           | 8.1
| Operating system      | Ubuntu

**Comment by samdark** [comment]
Do you have some time for a pull request?
