### ISSUE TITLE
Setting multi value attributes (MVA) through createCommand()

### ISSUE THREAD

**Issue by garyrutland** [yiisoft/yii2-sphinx#20]
Hey,

I'm trying to save an MVA attribute but can't seem to get it right, any ideas what's going wrong?

Yii::$app->sphinx->createCommand()->replace($this->indexTableName(), [
	'id' => 1,
	'test' => 'test',
	'mva' => implode(',', [1, 2, 3]),
]);

I've tried various ways of setting the MVa just so I don't get an error, but none have worked.
'mva' => implode(',', [1, 2, 3]),
'mva' => 0,
'mva' => '',

Thanks
Gary

**Comment by klimov-paul** [comment]
Don't use `implode` - pass MVA as array:
```php
Yii::$app->sphinx->createCommand()->replace($this->indexTableName(), [
    'id' => 1,
    'test' => 'test',
    'mva' => [1, 2, 3],
]);
```
