### ISSUE TITLE
ActiveQuery::search() fails if facet key does not match select part of facet

### ISSUE THREAD

**Issue by pahanini** [yiisoft/yii2-sphinx#28]
Here is an query example, this code tries to find min and max price in index:

```php 
$query = Item::find();
$query->addFacets([
    'price_min' => [
        'select' => 'price',
        'order' => ['price' => SORT_ASC],
        'limit' => 1
    ],
    'price_max' => [
        'select' => 'price',
        'order' => ['price' => SORT_DESC],
        'limit' => 1
    ],
]);
$query->search();
```

It will fail with 

```php
yii\base\ErrorException: Undefined index: price_min
/home/pahanini/projects/catalog/vendor/yiisoft/yii2-sphinx/Query.php:234
```

To solve this issue I have to use the same name for column name and facet key... This code works perfect:

$query = Item::find();
$query->addFacets([
    'price_min' => [
        'select' => 'price as price_min', // add as here
        'order' => ['price' => SORT_ASC],
        'limit' => 1
    ],
    'price_max' => [
        'select' => 'price as price_max', // add as here
        'order' => ['price' => SORT_DESC],
        'limit' => 1
    ],
]);
$query->search();

I suggest to make possible to use different names for key's name and select in this case.

**Comment by klimov-paul** [comment]
Please, check the last note from here:
https://github.com/yiisoft/yii2-sphinx/blob/master/docs/guide/usage-facets.md

**Comment by pahanini** [comment]
Ooops, I miss it! Gracias!

PS.  I guess this requirement is not obvious and may be it is a good idea to remove this limitation.

**Comment by klimov-paul** [comment]
>  it is a good idea to remove this limitation

I can't find a good way to do so. If you have an ideas, please share them.
