### ISSUE TITLE
findOne does not accept string as PK

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2-sphinx#30]
Source: http://sphinxsearch.com/wiki/doku.php?id=fields_and_attributes

> The first column is ALWAYS the document_id - and should be a unsigned 32 bit interger - it must be unique. (although sphinx can be compiled with 64 bit ID support). DONT define it as an attribute.

Error:
````sql
SQLSTATE[42000]: Syntax error or access violation: 1064 index rt: unsupported filter type 'string' on @id
The SQL being executed was: SELECT * FROM `rt` WHERE `id`='1810'

Error Info: Array
(
    [0] => 42000
    [1] => 1064
    [2] => index rt: unsupported filter type 'string' on @id
)
````

It's not mentioned in the documentation, but anyway, we know it's the primary key so we should not quote  that param.

**Comment by klimov-paul** [comment]
How did you compose this query?

**Comment by klimov-paul** [comment]
Closed unless more information arrives.

**Comment by razvanphp** [comment]
````php
UserSphinx::findOne($this->id);
````
inside the `User` AR model. This works only if I cast it to int here. Since this is specific to sphinx, the SDK should take care that it's always an int.

**Comment by klimov-paul** [comment]
Issue resolved by commit 19a02fc

**Comment by razvanphp** [comment]
Thank you!

Just a quick question, does it mean that now it does not quote any params in where clause?

**Comment by klimov-paul** [comment]
No, it process all values according to thier column types.
