### ISSUE TITLE
->andWhere('field', [])  0=1 error

### ISSUE THREAD

**Issue by disem** [yiisoft/yii2-sphinx#31]
https://github.com/yiisoft/yii2-sphinx/blob/master/QueryBuilder.php#L837
SQLSTATE[42000]: Syntax error or access violation: 1064 sphinxql: syntax error, unexpected CONST_INT, expecting IDENT (or 56 other tokens) near '0=1)

```php
$activeQuery->andWhere(['id' => []]);
$activeQuery->showMeta(false)->all();
```

**Comment by klimov-paul** [comment]
Issue resolved by commit 5f83c3b
