### ISSUE TITLE
Sphinx

### ISSUE THREAD

**Issue by dbd5** [yiisoft/yii2-sphinx#32]
Dear Paul,

Please forgive me - this is off topic but I'm desperate to get this resolved so I can use your great extension. 

Could you point me in the right direction to setup Sphinx correctly, this is the error I'm getting for all my effort:

"Can't open shared library '/usr/lib/mysql/plugin/ha_sphinx.so' (errno: 2 /usr/lib/mysql/plugin/ha_sphinx.so: undefined symbol: _ZTI7handler)"

My system is Ubuntu 14 64 Bit, I had followed the instructions here: https://brain.demonpenguin.co.uk/2015/04/30/adding-sphinxse-to-mysql-on-ubuntu-server/

The make seemed to have completed successfully so I got the error from MySQL at the point when I ran "INSTALL PLUGIN sphinx SONAME 'ha_sphinx.so'; 

Thank you in advance!

**Comment by klimov-paul** [comment]
http://sphinxsearch.com/docs/current/installing-debian.html

Best regards,
Klimov Paul

2015-07-06 20:37 GMT+03:00 dbd5 <notifications@github.com>:
