### ISSUE TITLE
Invalid UTF-8 sequence in argument error when calling json_encode() on sphinx record

### ISSUE THREAD

**Issue by rahil-geekunit** [yiisoft/yii2-sphinx#33]
There is a bug in Yii2 Sphinx Package which is causing  UTF-8 encoding issues.

This issue reported in detail on;
http://stackoverflow.com/questions/31266012/sphinx-invalid-utf-8-sequence-in-argument-error-when-calling-json-encode-on

**Comment by klimov-paul** [comment]
Does using of plain PDO (without extension) for the Sphinx query works for you?

**Comment by rahil-geekunit** [comment]
The issue was solved finally. It was a not a bug in Yii extension, but some configuration issue in the sphinx.conf.
As @klimov-paul  asked if the record is retrieved without using the Yii Sphinx query. And yes the problem was still faced even by querying with PDO.

By adding the correct set of codes into the charset_table option of an index in the config file, the issue can be resolved. It can take a bit of time to find which codes to choose from, but it will do just fine, if added correctly. One just need to know which characters set to choose from.

So after the configuration has been set up, and once index has been rotated, the insertions will be made in proper utf-8 format.
