### ISSUE TITLE
Doc mistake

### ISSUE THREAD

**Issue by NMFES** [yiisoft/yii2-sphinx#35]
https://github.com/yiisoft/yii2-sphinx/blob/master/docs/guide/usage-match.md

->match(new Expression(':match', ['match' => '@(content) ' . Yii::$app->sphinx->escapeMatchValue($_POST['search'])]))

Replace 'match' on ':match'.

**Comment by klimov-paul** [comment]
No, docs are correct. Prefixing parameters with `:` is not necessary.
