### ISSUE TITLE
Brackets error

### ISSUE THREAD

**Issue by dlasvazi** [yiisoft/yii2-sphinx#37]
Where using function find()->match($match), there are automatical run escapeMatchValue for $match value. But when '(' is quoted - sphinx says error:  index ******: syntax error, unexpected ')' near ')'.

**Comment by klimov-paul** [comment]
I am unable to reproduce the issue.
Please provide exact 'match' value, which cause a problem to you.

**Comment by dlasvazi** [comment]
$match = "бетон (ФБС)";
$products = Product::find()->match($match)->limit(10)->all();

output:
SQLSTATE[42000]: Syntax error or access violation: 1064 index productDelta,productMain: syntax error, unexpected ')' near ')'
The SQL being executed was: SELECT `text` FROM `product` WHERE MATCH('бетон \\(ФБС\\)') LIMIT 10

**Comment by klimov-paul** [comment]
Unable to reproduce.
Following unit test:
```php
public function testMatchSpecialCharValue2()
    {
        $connection = $this->getConnection();

        $query = new Query;
        $rows = $query->from('yii2_test_article_index')
            ->match("бетон (ФБС)")
            ->all($connection);
        $this->assertTrue(is_array($rows)); // no query error
    }
```
passes correctly.

It must be the issue at the Sphinx server side. Try to upgrade.

**Comment by dlasvazi** [comment]
MySQL [(none)]> SELECT count(*) FROM `product` where match('бетон \\(ФБС\\)');
ERROR 1064 (42000): index productDelta,productMain: syntax error, unexpected ')' near ')'
MySQL [(none)]> SELECT count(*) FROM `product` where match('бетон \\(фбс\\)');
+----------+
| count(*) |
+----------+
|        6 |
+----------+
1 row in set (0.65 sec)

Something wrong with character case. I can't understand.
