### ISSUE TITLE
Create a function like BuildExcerpts 

### ISSUE THREAD

**Issue by qwerty75371** [yiisoft/yii2-sphinx#41]
It would be great if the extension has a function like BuildExcerpts, you can find it https://code.google.com/p/sphinxsearch/source/browse/trunk/api/sphinxapi.php

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-sphinx/blob/master/docs/guide/usage-snippets.md

**Comment by qwerty75371** [comment]
Thank you for your link, but I am not sure that they are the same. 

Snippet lets me do some actions with $rows (incoming parameter), but BuildExcerpts takes parameters it needs and highlights words using morphology

**Comment by dellert** [comment]
I have same question
there is no function like BuildExcerpts

**Comment by klimov-paul** [comment]
@dellert, specially for you: "excerpt" and "snippet" are SYNONYMS.
Use `callSnippets()`.

**Comment by dellert** [comment]
@klimov-paul, Snippet lets me do some actions with $rows (incoming parameter), but BuildExcerpts takes parameters it needs and highlights words using morphology. 
Can callSnippets() do it?

**Comment by dellert** [comment]
@klimov-paul, can you help me?
what am I doing wrong?

` public function getSnippetSource()
    {
        return $this->search_text;
    }


self::find()->match(new Expression(':search_text', [
            'search_text' => '@(search_text) ' . Yii::$app->sphinx->escapeMatchValue($text)
        ]))->snippetCallback(function($rows) {
            $result = [];

            foreach ($rows as $row) {
                $result[] = $row['search_text'];
            }

            return $result;
        })->snippetOptions([
            'before_match' => '<strong>',
            'after_match' => '</strong>',
            'chunk_separator' => '...',
        ])->all();
`

But snippet value is plain text without highlights

**Comment by klimov-paul** [comment]
If you can not read the documentation - I can not help you. I am sorry.
