### ISSUE TITLE
Error in QueryBuilder for sphinx

### ISSUE THREAD

**Issue by VGrigoryev** [yiisoft/yii2-sphinx#43]
Method buildWithin have a mistake.
If set sorting by ASC, displayed error:
> SQLSTATE [42000]: Syntax error or access violation: 1064 index INDEXNAME: no sort order defined

**Comment by klimov-paul** [comment]
Issue resolved by commit 1152bb08267ca2d1fc06c2c5369d19ccc2a98ac9
