### ISSUE TITLE
FACET ORDER

### ISSUE THREAD

**Issue by nekulin** [yiisoft/yii2-sphinx#44]
You cannot sort an array, because it is not finds the index of the result array

Example: 
	FACET brand_id ORDER BY COUNT(*) DESC
	// for
	$rawFacetResult['value'] = $rawFacetResult[strtolower($facet['value'])];
	$facet['value'] == 'brand_id ORDER BY COUNT(*) DESC' // error notice index

**Comment by klimov-paul** [comment]
Please, provide the exact code to reproduce the problem.

**Comment by klimov-paul** [comment]
Unable to reproduce. 
There is a unti test, which covers facet with order by:
https://github.com/yiisoft/yii2-sphinx/blob/master/tests/QueryTest.php#L404
It is passing.
