### ISSUE TITLE
Sphinx if not working in select

### ISSUE THREAD

**Issue by guerro123** [yiisoft/yii2-sphinx#52]
Hello,

Sphinx IF function (http://sphinxsearch.com/docs/current.html#expr-func-if) does not work with Yii:

    $query = new Query();
    $query->select('IF(1=1,1,0) as x')
           ->from('myindex');
    $query->createCommand()->queryAll();

**Comment by klimov-paul** [comment]
Same as https://github.com/yiisoft/yii2/issues/8276
