### ISSUE TITLE
Problem with column, which has data type bigint

### ISSUE THREAD

**Issue by andynador** [yiisoft/yii2-sphinx#55]
Good day. 
I have table with column id, which has type bigint. I create index for this table. When I try to filter data by id, I got error
`SQLSTATE[42000]: Syntax error or access violation: 1064 index company_index: unsupported filter type 'string' on @id
The SQL being executed was: SELECT * FROM company_index WHERE id='1'`
Problem, of course, in extra quotes in WHERE clause, but manually I don't pass it. I find reason of the problem - I have 32-bit version of PHP, OS WIndows. In You extension I found code, which get DB-type of column and return its PHP-type. For column bigint You have condition - if PHP-version is 64-bit, return integer, else - return string (Class **yii\sphinx\Schema**, lines 431-432). And then, after got PHP-type, code generates SQL-query, which has filter with passed value and cast it to PHP-type (Class **yii\sphinx\ColumnSchema**, lines 98-108). In my system, this code generates string type for bigint column, value has been escaped with quotes and then I got SQL error. I think, it's a little bug, because in **ColumnSchema** You don't check type of column. How can I fix this problem and not change type of column to integer?

**Comment by klimov-paul** [comment]
There is not other solution for this, but usage of 64-bit system or regular 'int' type.
With 32-bit system bigint data may overflow PHP integer limit causing fatal error.

**Comment by andynador** [comment]
Ok, thank You for help!

**Comment by zakdma** [comment]
@klimov-paul 
I dont think that is correct decision.
> With 32-bit system bigint data may overflow PHP integer limit causing fatal error.
It MAY cause (mostly not) but it DO cause error just now. I have the same issue. Maybe my base will not reach integer that overflow int type but it can't work at all NOW not in the imaginary future.
