### ISSUE TITLE
How to insert data in table, not in index?

### ISSUE THREAD

**Issue by andynador** [yiisoft/yii2-sphinx#57]
I have model Company
```
class Company extends \yii\sphinx\ActiveRecord
{
    public static function tableName()
    {
        return 'company';
    }

    public static function indexName()
    {
        return 'company_index';
    }
   ...
}
```
And I want to insert data in master-table, not in index. When I set fields with some values and call method **save**, I got error
> index 'company_index' does not support INSERT

I have bad idea to create another model, which extends  **\yii\db\ActiveRecord** class, and use it for insert, but I don't want to duplicate code in two models.  Another idea - create method, for example, saveInTable and use it, but iin this way I need to clone and rename methods, such **insert**, **insertInternal**, **update**, **updateInternal** from **\yii\db\ActiveRecord**, which is not good idea, I think. Maybe anyone has better ideas or implement which task?

**Comment by klimov-paul** [comment]
@andynador, please use <a href="http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/">Official Yii 2 forum</a> to ask a questions - GitHub is a bug tracking system.
