### ISSUE TITLE
sphinx distributed  match error bug

### ISSUE THREAD

**Issue by hhy5861** [yiisoft/yii2-sphinx#58]
select code:
![2](https://cloud.githubusercontent.com/assets/8274977/14350958/0fd56644-fcff-11e5-916f-653ac51fb127.png)

result error:
![1](https://cloud.githubusercontent.com/assets/8274977/14350981/3bb436f0-fcff-11e5-9595-8dad7001ba67.png)

mysql -h 192.168.110.40 -P 9306 shell connection select success;
![3](https://cloud.githubusercontent.com/assets/8274977/14351071/cc7373cc-fcff-11e5-9f8c-02c3dfda5cc8.png)

**Comment by klimov-paul** [comment]
What exact SQL was executed?

**Comment by hhy5861** [comment]
rowsql log:

SHOW TABLES
DESCRIBE `index_car_keyword`

this is my code:
                $query = new \yii\sphinx\Query();
		$query->select(['car_id'])->from('index_car_keyword');

		$query->match(new Expression(':match', ['match' => '@(keyword) "fengtian"']));
		$result = $query->all();

**Comment by klimov-paul** [comment]
In that case where 'near `192.168.110.42`...' comes from?

Please, provide full stack trace.

**Comment by hhy5861** [comment]
index index_car_keyword
{
    type=distributed  
    agent=192.168.110.42:9312|192.168.110.41:9312:index_car_keyword
    agent=192.168.110.42:9312|192.168.110.41:9312:index_car_keyword_delta
    ha_strategy=nodeads
}

searchd
{
        listen              = 9312
	    listen              = 9306:mysql41
    	log                 = /data/sphinx/logs/searchd.log
    	query_log           = /data/sphinx/logs/query.log
    	read_timeout        = 5
    	max_children        = 300
    	pid_file            = /data/sphinx/logs/searchd.pid
    	seamless_rotate     = 1
    	preopen_indexes     = 1
    	unlink_old          = 1
    	mva_updates_pool    = 1M
    	max_packet_size     = 32M
    	max_filters         = 256
    	max_filter_values   = 4096
    	binlog_path         = /data/sphinx/logs/
}

**Comment by klimov-paul** [comment]
Exception stack trace please.

**Comment by hhy5861** [comment]
If no match is ok!

**Comment by klimov-paul** [comment]
Do you understand my words?

**Comment by hhy5861** [comment]
2016-04-07 21:50:21 [127.0.0.1][-][-][trace][yii\base\Application::bootstrap] Bootstrap with yii\log\Dispatcher
2016-04-07 21:50:21 [127.0.0.1][-][-][trace][yii\web\UrlRule::parseRequest] Request parsed with URL rule: <controller:^(?!api)\w+>/<action:\w+>
2016-04-07 21:50:21 [127.0.0.1][-][-][trace][yii\web\Application::handleRequest] Route requested: 'api/auth/index'
2016-04-07 21:50:21 [127.0.0.1][-][-][trace][yii\base\Module::getModule] Loading module: api
2016-04-07 21:50:21 [127.0.0.1][-][-][trace][yii\base\Controller::runAction] Route to run: api/auth/index
2016-04-07 21:50:21 [127.0.0.1][-][-][info][yii\filters\RateLimiter::beforeAction] Rate limit skipped: user not logged in.
2016-04-07 21:50:21 [127.0.0.1][-][-][trace][yii\base\Action::runWithParams] Running action: api\controllers\action\auth\IndexAction::run()
2016-04-07 21:50:21 [127.0.0.1][-][-][info][yii\db\Command::query] SHOW TABLES
    in /Volumes/Code/php/base-auth/app/module/api/controllers/action/auth/IndexAction.php:22
2016-04-07 21:50:21 [127.0.0.1][-][-][info][yii\db\Connection::open] Opening DB connection: mysql:host=116.228.172.169;port=9306;
    in /Volumes/Code/php/base-auth/app/module/api/controllers/action/auth/IndexAction.php:22
2016-04-07 21:50:22 [127.0.0.1][-][-][info][yii\db\Command::query] DESCRIBE `index_car_keyword`
    in /Volumes/Code/php/base-auth/app/module/api/controllers/action/auth/IndexAction.php:22
2016-04-07 21:50:22 [127.0.0.1][-][-][info][yii\db\Command::query] DESCRIBE `192.168.110.42:9312:index_car_keyword`
    in /Volumes/Code/php/base-auth/app/module/api/controllers/action/auth/IndexAction.php:22
2016-04-07 21:50:22 [127.0.0.1][-][-][error][yii\db\Exception] exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 sphinxql: syntax error, unexpected $undefined, expecting IDENT (or 93 other tokens) near '`192.168.110.42:9312:index_car_keyword`'' in /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Command.php:837
Stack trace:
#0 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Command.php(837): PDOStatement->execute()
#1 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Command.php(359): yii\db\Command->queryInternal('fetchAll', NULL)
#2 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(453): yii\db\Command->queryAll()
#3 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(92): yii\sphinx\Schema->findColumns(Object(yii\sphinx\IndexSchema))
#4 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(153): yii\sphinx\Schema->loadIndexSchema('192.168.110.42:...')
#5 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(474): yii\sphinx\Schema->getIndexSchema('192.168.110.42:...')
#6 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(92): yii\sphinx\Schema->findColumns(Object(yii\sphinx\IndexSchema))
#7 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(153): yii\sphinx\Schema->loadIndexSchema('index_car_keywo...')
#8 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Connection.php(79): yii\sphinx\Schema->getIndexSchema('index_car_keywo...', false)
#9 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/QueryBuilder.php(1241): yii\sphinx\Connection->getIndexSchema('index_car_keywo...')
#10 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/QueryBuilder.php(562): yii\sphinx\QueryBuilder->getIndexSchemas(Array)
#11 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/QueryBuilder.php(108): yii\sphinx\QueryBuilder->buildWhere(Array, NULL, Array, Object(yii\db\Expression))
#12 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Query.php(174): yii\sphinx\QueryBuilder->build(Object(yii\sphinx\Query))
#13 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Query.php(206): yii\sphinx\Query->createCommand(NULL)
#14 /Volumes/Code/php/base-auth/app/module/api/controllers/action/auth/IndexAction.php(22): yii\db\Query->all()
#15 [internal function]: api\controllers\action\auth\IndexAction->run()
#16 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#17 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)
#18 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('index', Array)
#19 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('api/auth/index', Array)
#20 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 /Volumes/Code/php/base-auth/index/web/api/index.php(18): yii\base\Application->run()
#22 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 sphinxql: syntax error, unexpected $undefined, expecting IDENT (or 93 other tokens) near '`192.168.110.42:9312:index_car_keyword`'
The SQL being executed was: DESCRIBE `192.168.110.42:9312:index_car_keyword`' in /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php:526
Stack trace:
#0 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Command.php(852): yii\sphinx\Schema->convertException(Object(PDOException), 'DESCRIBE `192.1...')
#1 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Command.php(359): yii\db\Command->queryInternal('fetchAll', NULL)
#2 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(453): yii\db\Command->queryAll()
#3 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(92): yii\sphinx\Schema->findColumns(Object(yii\sphinx\IndexSchema))
#4 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(153): yii\sphinx\Schema->loadIndexSchema('192.168.110.42:...')
#5 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(474): yii\sphinx\Schema->getIndexSchema('192.168.110.42:...')
#6 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(92): yii\sphinx\Schema->findColumns(Object(yii\sphinx\IndexSchema))
#7 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Schema.php(153): yii\sphinx\Schema->loadIndexSchema('index_car_keywo...')
#8 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Connection.php(79): yii\sphinx\Schema->getIndexSchema('index_car_keywo...', false)
#9 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/QueryBuilder.php(1241): yii\sphinx\Connection->getIndexSchema('index_car_keywo...')
#10 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/QueryBuilder.php(562): yii\sphinx\QueryBuilder->getIndexSchemas(Array)
#11 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/QueryBuilder.php(108): yii\sphinx\QueryBuilder->buildWhere(Array, NULL, Array, Object(yii\db\Expression))
#12 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2-sphinx/Query.php(174): yii\sphinx\QueryBuilder->build(Object(yii\sphinx\Query))
#13 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/db/Query.php(206): yii\sphinx\Query->createCommand(NULL)
#14 /Volumes/Code/php/base-auth/app/module/api/controllers/action/auth/IndexAction.php(22): yii\db\Query->all()
#15 [internal function]: api\controllers\action\auth\IndexAction->run()
#16 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array(Array, Array)
#17 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\Action->runWithParams(Array)
#18 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('index', Array)
#19 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('api/auth/index', Array)
#20 /Volumes/Code/php/base-auth/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 /Volumes/Code/php/base-auth/index/web/api/index.php(18): yii\base\Application->run()

**Comment by klimov-paul** [comment]
Which Sphinx Server version do you use?

**Comment by hhy5861** [comment]
centos 7.1
sphinx version 2.2.10

**Comment by klimov-paul** [comment]
There is no way to extract schema from remote agent, since there is no ability to connect ot it.
Such action require usage of Sphinx internal protocol and having a proper credentials.

In order to make schema detection to function properly you must create a dummy local index, which can be empty, and add it to your distibuted index config.

Still there should be a bypass for 'agent'.

**Comment by klimov-paul** [comment]
Resolved by commit 0d6701d9e376d61452fffd9b479abd39c795d381
