### ISSUE TITLE
Yii2 sphinx extension show less results then native query 

### ISSUE THREAD

**Issue by johndoejdg** [yiisoft/yii2-sphinx#59]
### What steps will reproduce the problem?
        $query = new Query();
        $query = $query->select(['id'])
            ->from('main')
            ->match('23|24');

 With yii2 return only 2 rows! When I open console mysql client and run query it return 20 rows:
SELECT id FROM main WHERE MATCH('23|24'); 

### What's expected?
I expect to see same results for both cases.

### Additional info
| Yii vesion       | 2.0.7
| PHP version      |  7.0.5 x86_64
| Operating system | Linux 4.5.0-1 
"yiisoft/yii2-sphinx": 2.0.5

**Comment by klimov-paul** [comment]
Unable to reproduce

**Comment by johndoejdg** [comment]
I solved it problem by refactoring query to follow view:
'SELECT * FROM main WHERE MATCH (\''.$keyword.'\')'

Maybe it can help someone in feature.

**Comment by johndoejdg** [comment]
Better solution:       
 $sql = 'SELECT * FROM main WHERE MATCH (:keyword)';
 $params = [
     'keyword' => $keyword
 ];

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-sphinx/blob/master/docs/guide/usage-match.md

**Comment by johndoejdg** [comment]
Thank you, now it work correctly. Refactored query:
        $query = $query->select(['id'])
            ->from('main')
            ->match(new Expression("'$keyword'"));
