### ISSUE TITLE
Yii2 snippets with match mode

### ISSUE THREAD

**Issue by goodini** [yiisoft/yii2-sphinx#61]
when used at the same time match and snippetCallback, does not change the setting :qp2

in yii\sphinx\QueryBuilder

$params[$matchParamName] = $match; (411 string)

replaced by

if ($match instanceof Expression) {
$params[$matchParamName] = $match->params['match'];
} else {
$params[$matchParamName] = $match;
}

**Comment by klimov-paul** [comment]
Resolved by commit 9baafbb81cc571051b1ab43957f31c314d2d2ef1
