### ISSUE TITLE
Integers should be handled the same way as floats

### ISSUE THREAD

**Issue by maz0717** [yiisoft/yii2-sphinx#69]
### What steps will reproduce the problem?
->andFilterWhere('>=','year',$integer_var);

### What's expected?
The query to work.

### What do you get instead?
SQLSTATE[42000]: Syntax error or access violation: 1064 sphinxql: syntax error, unexpected QUOTED_STRING, expecting CONST_INT or CONST_FLOAT or DOT_NUMBER or '-' near ''1400') AND (`issue_year` <= '1500')) AND (`is_forsale`=1)) ORDER BY `title` ASC LIMIT 25; SHOW META'

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | 2.0.10
| Yii Sphinx version    |  lastest from composer
| Sphinx server version | 2.2.11
| PHP version           | 7.0.12
| Operating system      | CentOS 7

**Comment by klimov-paul** [comment]
Resolved by commit 4625dd0e1df3230368dd99f1bbe1e36d56ff0346
