### ISSUE TITLE
andMatch does not ignore empty operands

### ISSUE THREAD

**Issue by maz0717** [yiisoft/yii2-sphinx#70]
### What steps will reproduce the problem?
$query->andMatch(['title' => $this->title]);

### What's expected?
The match to be ignored as andFilterWhere does in ActiveQuery.

### What do you get instead?
Empty results.

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | 2.0.10
| Yii Sphinx version    |  lastest from composer
| Sphinx server version | 2.2.11
| PHP version           | 7.0.12
| Operating system      | CentOS 7

**Comment by klimov-paul** [comment]
No this is expected behavior.

**Comment by klimov-paul** [comment]
Reconsidered issue as an enhancement: `MatchExpression::andFilterMatch()` method can be added

**Comment by klimov-paul** [comment]
Resolved by commit 2d828f41bc73556b32efe474cd4229eeb58b99cd
