### ISSUE TITLE
2.0.8 tag?

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii2-sphinx#72]
My composer.json for deployment has 

        "yiisoft/yii2-sphinx": "dev-master",

because i need the timestamp type fix d989eff548253b4a1f3f14414f59eb842e72dc1d

I think dev-master is today no less stable than 2.0.7, so could you tag it?

**Comment by samdark** [comment]
@klimov-paul seems there are no other issues so I think it's a good idea to tag a release.

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-sphinx/releases/tag/2.0.8
