### ISSUE TITLE
Runtime -> Real-time

### ISSUE THREAD

**Issue by Renkas** [yiisoft/yii2-sphinx#73]
Why is Sphinx Real-time indexes named runtime indexes in this extension?

Maybe the naming should be changed to match Sphinx so that there would be no confusion? I had to double check that these are the same thing - kind of unneccessary step.

http://sphinxsearch.com/docs/current.html#rt-indexes

**Comment by klimov-paul** [comment]
Resolved by commit b07b7bbe8446b8a2d309e335f55c53fae194abe8
Thank you for the report.
