### ISSUE TITLE
empty MVA field population error

### ISSUE THREAD

**Issue by batyrmastyr** [yiisoft/yii2-sphinx#75]
### What steps will reproduce the problem?
Populate ActiveRecord instance with empty MVA attribute with empty value. Check assigned value of this attribute.

### What's expected?
Empty array ("[]")

### What do you get instead?
Array with null element ("[NULL]")

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | 2.0.12
| Yii Sphinx version    | 2.0.8
| Sphinx server version | 2.3.2
| PHP version           | 7.1.3
| Operating system      | Debian Jessie

**Comment by klimov-paul** [comment]
Resolved by commit e4d162538b8bdf5c31be873d60c469ed9d99c40f
