### ISSUE TITLE
Method batch() not working

### ISSUE THREAD

**Issue by iluxaar** [yiisoft/yii2-sphinx#79]
The index contains 500 documents.

```
foreach (Index::find()->batch(100) as $batch) {
    echo(count($batch)); // 20
}
```
When increase the limit:
```
foreach (Index::find()->limit(100000)->batch(100) as $batch) {
    echo(count($batch)); // 500
}
```
How to choose all 500 documents in parts of 100 pieces?

| Yii version           | 2.0.11
| Yii Sphinx version    | 2.0.6
| Sphinx server version | 2.2.11
| PHP version           | 5.6
| Operating system      | ubuntu 14

**Comment by klimov-paul** [comment]
Unable to reproduce.
Added a unit tests for verification:
https://github.com/yiisoft/yii2-sphinx/blob/master/tests/BatchQueryResultTest.php#L85-L93

**Comment by iluxaar** [comment]
```
    // limit increase :
    $query = (new Query())
        ->from('yii2_test_article_index')
        ->limit(200);
    $allRows = [];
    foreach ($query->batch(100, $db) as $rows) {
        $this->assertCount(100, $rows);
        $allRows = array_merge($allRows, $rows);
    }
    $this->assertCount(200, $allRows);
```

**Comment by klimov-paul** [comment]
Makes no difference: such test passes just as well.
