### ISSUE TITLE
How to highlight searching words

### ISSUE THREAD

**Issue by zhaosi2017** [yiisoft/yii2-sphinx#81]
Hello, 

I installed extension yii2-sphinx, and it works great.

But I have a question, how to highlight searched words?
If to look at code[dot]google[dot]com/p/sphinxsearch/source/browse/trunk/api/sphinxapi.php , we can find a function BuildExcerpts, which let you set several params: before_match and after_match. 

Does this extension have any function like BuildExcerpts?

I hope for your help, thank you

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-sphinx/blob/master/docs/guide/usage-snippets.md

**Comment by zhaosi2017** [comment]
I have readed the guide. but I just can't understand the function of getSnippetSource.
I will appreciate that you give a example which data return of the function of getSnippetSource. Thank you!

**Comment by klimov-paul** [comment]
https://github.com/yiisoft/yii2-sphinx/blob/master/tests/data/ar/ArticleIndex.php#L35-L38
https://github.com/yiisoft/yii2-sphinx/blob/master/tests/ExternalActiveRelationTest.php#L78-L86

**Comment by zhaosi2017** [comment]
The code is hard to use. Why don't just follow the original forum form. I just want to highlight the keyswords .  Why don't just user options attribute like this
$options = [
            "before_match"  => "<span style='font-weight:bold;color:red'>",
            "after_match"  => "</span>",
        ];

instead of 
     *$query = new Query();
     * $query->from('idx_item')
     *     ->match('pencil')
     *     ->snippetCallback(function ($rows) {
     *         $result = [];
     *         foreach ($rows as $row) {
     *             $result[] = file_get_contents('/path/to/index/files/' . $row['id'] . '.txt');
     *         }
     *         return $result;
     *     })
     *     ->all();

I really confuse that what the data  does the file of txt return.  I think it's maybe the html code like "<b> </b>". but it not work.

The unittest  you prodive. I don't realy understand. I hope for your help, thank you!
