### ISSUE TITLE
Expression not correct work

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2-sphinx#82]
### What steps will reproduce the problem?
I'm try to use yii\db\expression in yii\sphinx\ActiveQuery like ```'alias'=>new Expression("field/5")```

### What's expected?
expect result sql ```field/5 as alias```
### What do you get instead?
no alias in result sql

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           |2.0.12
| Yii Sphinx version    |from composer
| Sphinx server version |Sphinx 2.2.9-id64-release (rel22-r5006)
| PHP version           |7
| Operating system      |ubuntu 16

**Comment by klimov-paul** [comment]
Resolved by commit e7571ed3da6c4709a21d016203afceb389fe5677
