### ISSUE TITLE
ActiveDataProvider and additional select field

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2-sphinx#85]
### What steps will reproduce the problem?
view
```
echo \yii\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'test1',
    ],
]);
```
model
```
use yii\db\Expression;
use yii\sphinx\ActiveDataProvider;
use yii\sphinx\ActiveRecord;

class Item1 extends ActiveRecord
{
    public $test1;

    public static function indexName()
    {
        return 'item';
    }

    public function getProvider()
    {
        $query = static::find();

        $query->select([
            'test1' => new Expression('somefield/10'),
        ]);

        $query->andHaving(['>=', 'test1', 0]);

        return new ActiveDataProvider([
            'query' => $query,
        ]);
    }
}
```
### What's expected?
correct work
### What do you get instead?
```
Syntax error or access violation: 1064 can not use HAVING with attribute not related to GROUP BY
The SQL being executed was: SELECT COUNT(*) FROM `item` HAVING `test1` >= 0
```
for some reason new column `test` not pass to count query

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           |2.0.12
| Yii Sphinx version    |2.0.8
| Sphinx server version |Sphinx 2.2.9-id64-release (rel22-r5006)
| PHP version           |7
| Operating system      |ubuntu 16

**Comment by samdark** [comment]
The message explains what's wrong clearly.

**Comment by nicdnepr** [comment]
Where is section for sphinx questions in forum http://www.yiiframework.com/forum/?
As I understand this section is for any issues for yii2-sphinx, not for yii questions

**Comment by nicdnepr** [comment]
Also I don't ask how to do something, but ask why I get wrong action for correct working code

**Comment by samdark** [comment]
http://www.yiiframework.com/forum/index.php/forum/42-general-discussions/

**Comment by samdark** [comment]
It's not correct working code. You're using HAVING without GROUP BY. That is now allowed in SQL.
