### ISSUE TITLE
andFilterWhere and number from querystring

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2-sphinx#86]
### What steps will reproduce the problem?
```
$query=Index::find();
$price=$_GET['price'];
$query->andFilterWhere(['>=', 'price', $price]);
```
for example url is filter?price=5
### What's expected?
```select * from index where price >=5```
### What do you get instead?
```
 Syntax error or access violation: 1064 sphinxql: syntax error, unexpected QUOTED_STRING, expecting CONST_INT or CONST_FLOAT or DOT_NUMBER or '-' near ''5'
SELECT * FROM `sticker` WHERE `price` >= '5' 
```
### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           |2.0.12
| Yii Sphinx version    |2.0.8
| Sphinx server version |Sphinx 2.2.11-id64-release (95ae9a6)
| PHP version           |7
| Operating system      |ubuntu 16

**Comment by klimov-paul** [comment]
Unable to reproduce. This case is covered by unit test:
https://github.com/yiisoft/yii2-sphinx/blob/master/tests/QueryTest.php#L750-L771

**Comment by nicdnepr** [comment]
Maybe depends on sphinx version?
in sphinx console this query ```SELECT  `pricecsmoney` AS `price` FROM `sticker` WHERE price >= '5'``` is fail  with error ```sphinxql: syntax error, unexpected QUOTED_STRING, expecting CONST_INT or CONST_FLOAT or DOT_NUMBER or '-' near ''5''```

**Comment by nicdnepr** [comment]
Guess I found problem
In my query I use alias 
```
$query=new Query();
$query->select(['price'=>'pricecsmoney','pricecsmoney']);
$query->from('sticker');
$query->andFilterWhere(['>=', 'price', '5']);
$query->andFilterWhere(['>=', 'pricecsmoney', '5']);
$query->all();
```
```$query->andFilterWhere(['>=', 'price', '5']);``` this not work
``` $query->andFilterWhere(['>=', 'pricecsmoney', '5']);``` this is work

Maybe this is sphinx bug?

**Comment by samdark** [comment]
Could be. To verify you can use any MySQL client (even mysql CLI) to connect to Sphinx and make a query.
