### ISSUE TITLE
ActiveRecord: Fields that are both rt_field and rt_attr_string do not get "replaced"

### ISSUE THREAD

**Issue by maz0717** [yiisoft/yii2-sphinx#90]
### What steps will reproduce the problem?
Create an index with a field that is both a rt_field and rt_attr_string.  This is the recommended way to set up fields that you want to both search and order by.

$ar = Index::findOne(['id' => 1]);
$ar->field = 'blah';
$ar->save();

### What's expected?
A replace query to be run.

### What do you get instead?
An insert query is run.

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | latest
| Yii Sphinx version    | latest
| Sphinx server version |2.2.11
| PHP version           | 7.0.20
| Operating system      | MacOS High Sierra

### Notes
If you do a describe statement on an index with a field that is both rt_field and rt_attr_string, you will receive two entries.  The Schema::findColumns function should detect duplicate fields and merge the definitions instead of overwriting a previous definition with a new one.

An alternative is to modify ActiveRecord::updateInternal to check if the field type is a string instead of checking $columnSchema->isField.

### Hotfix
I have replaced ActiveRecord.php line 506 which currently reads:
if($columnSchema->isField) {
with
if($columnSchema->type === 'string') {

**Comment by klimov-paul** [comment]
How does Sphinx config for your index look like?

**Comment by maz0717** [comment]
`
index raremaps {
    type                = rt
    rt_mem_limit        = 32M

    dict = keywords

    html_strip      = 1
    morphology      = stem_en
    # min_prefix_len = 3
    # min_infix_len   = 2
    # dict = keywords
    index_exact_words = 1
    expand_keywords = 1

    min_infix_len   = 3
    charset_table   = 0..9, A..Z->a..z, a..z, \
        U+C0->a, U+C1->a, U+C2->a, U+C3->a, U+C4->a, U+C5->a, U+C6->a, \
        U+C7->c,U+E7->c, U+C8->e, U+C9->e, U+CA->e, U+CB->e, U+CC->i, \
        U+CD->i, U+CE->i, U+CF->i, U+D0->d, U+D1->n, U+D2->o, U+D3->o, \
        U+D4->o, U+D5->o, U+D6->o, U+D8->o, U+D9->u, U+DA->u, U+DB->u, \
        U+DC->u, U+DD->y, U+DE->t, U+DF->s, \
        U+E0->a, U+E1->a, U+E2->a, U+E3->a, U+E4->a, U+E5->a, U+E6->a, \
        U+E7->c,U+E7->c, U+E8->e, U+E9->e, U+EA->e, U+EB->e, U+EC->i, \
        U+ED->i, U+EE->i, U+EF->i, U+F0->d, U+F1->n, U+F2->o, U+F3->o, \
        U+F4->o, U+F5->o, U+F6->o, U+F8->o, U+F9->u, U+FA->u, U+FB->u, \
        U+FC->u, U+FD->y, U+FE->t, U+FF->s,

    path                = /usr/local/var/sphinx/raremaps

    rt_attr_uint        = inventory_id
    rt_field            = title
    rt_attr_string      = title
    rt_field            = stock_num
    rt_attr_string      = stock_num
    rt_field            = creator
    rt_attr_string      = creator
    rt_field            = category
    rt_attr_bool        = is_forsale
    rt_attr_bool        = is_archive
    rt_attr_bool        = is_hidden
    rt_attr_timestamp   = publish_date
    rt_attr_uint        = issue_year
    rt_field            = issue_year_str
    rt_field            = issue_place
    rt_field            = publisher
    rt_attr_float       = image_size_height
    rt_attr_float       = image_size_width
    # rt_field          = image_size_info
    rt_attr_float       = price
    rt_attr_float       = sold_price
    rt_attr_float       = original_price

    rt_attr_uint        = copy_id

    rt_attr_multi       = category_id
    rt_attr_multi       = creator_id

    rt_field            = short_title
    rt_field            = foreign_title
    rt_field            = description
    rt_field            = reference
    rt_field            = keywords

    rt_attr_timestamp   = acquisition_date
    rt_attr_timestamp   = sold_date
    rt_field            = physical_location
    rt_attr_string      = physical_location
    rt_attr_uint        = admin_status_id
    rt_field            = admin_status
    rt_attr_string      = admin_status
    rt_attr_uint        = type_id
    rt_field            = type
    rt_attr_string      = type
    rt_attr_multi       = partner_id
    rt_field            = partnership
    rt_attr_string      = partnership
}
`

**Comment by maz0717** [comment]
Here is the describe from that index:
MySQL [(none)]> describe raremaps;
+-------------------+-----------+
| Field             | Type      |
+-------------------+-----------+
| id                | bigint    |
| title             | field     |
| stock_num         | field     |
| creator           | field     |
| category          | field     |
| issue_year_str    | field     |
| issue_place       | field     |
| publisher         | field     |
| short_title       | field     |
| foreign_title     | field     |
| description       | field     |
| reference         | field     |
| keywords          | field     |
| physical_location | field     |
| admin_status      | field     |
| type              | field     |
| partnership       | field     |
| inventory_id      | uint      |
| issue_year        | uint      |
| copy_id           | uint      |
| admin_status_id   | uint      |
| type_id           | uint      |
| image_size_height | float     |
| image_size_width  | float     |
| price             | float     |
| sold_price        | float     |
| original_price    | float     |
| publish_date      | timestamp |
| acquisition_date  | timestamp |
| sold_date         | timestamp |
| title             | string    |
| stock_num         | string    |
| creator           | string    |
| physical_location | string    |
| admin_status      | string    |
| type              | string    |
| partnership       | string    |
| category_id       | mva       |
| creator_id        | mva       |
| partner_id        | mva       |
| is_forsale        | bool      |
| is_archive        | bool      |
| is_hidden         | bool      |
+-------------------+-----------+
43 rows in set (0.00 sec)

Docs suggest that you can have an attribute and a field with the same name. Sphinx forums confirm it.

**Comment by klimov-paul** [comment]
Resolved by commit d2db0b2da39043614eec76b563aed932283f7188
