### ISSUE TITLE
Compatibility with php 7.2

### ISSUE THREAD

**Issue by Simutin32** [yiisoft/yii2-sphinx#92]
### What steps will reproduce the problem?
(new \yii\sphinx\Query())->where(['in', 'status', [101, 103, 105]])->all()
### What's expected?
result array
### What do you get instead?
PHP Warning – yii\base\ErrorException
in vendor/yiisoft/yii2-sphinx/QueryBuilder.php at line 940
count(): Parameter must be an array or an object that implements Countable

### Additional info

| Q                     | A
| --------------------- | ---
| Yii version           | 2.0.13.1
| Yii Sphinx version    | 2.0.9
| Sphinx server version | 2.2.9
| PHP version           | 7.2.0 RC6
| Operating system      | Ubuntu 16.04.3 LTS

**Comment by dmirogin** [comment]
Thanks!
Should be fixed like here https://github.com/yiisoft/yii2/pull/14959

**Comment by klimov-paul** [comment]
Resolved by commit b4b507e01d821a687310a9d18174279112435cb7
